export const OrderArray = [
	{
		id: "order1212",
		supplier: "East cost fruits",
		shipping_date: "Thu, Feb 10",
		total: 15000,
		categories: ["fruits", "vegitables"],
		department: "300-30-1130",
		status: "Awaiting your approval",
		products: [
			{
				image: "/images/apple.png",
				name: "Product1",
				brand: "Home Black",
				price: 30,
				quantity: 0,
				total: 0,
				prod_status: "pending",
			},
			{
				image: "/images/avocado.jpg",
				name: "Product2",
				brand: "Home Blue",
				price: 120,
				quantity: 3,
				total: 360,
				prod_status: "pending",
			},
			{
				image: "/images/apple.png",
				name: "Product4",
				brand: "Home Red",
				price: 300,
				quantity: 4,
				total: 1200,
				prod_status: "pending",
			},
			{
				image: "/images/avocado.jpg",
				name: "Product5",
				brand: "Home Black",
				price: 200,
				quantity: 10,
				total: 2000,
				prod_status: "pending",
			},
		],
	},
	{
		id: "order14904",
		supplier: "Order XYZ",
		shipping_date: "Thu, Feb 15",
		total: 15000,
		categories: ["fruits", "vegitables"],
		department: "300-30-1130",
		status: "Awaiting your approval",
		products: [
			{
				image: "/images/apple.png",
				name: "Product1",
				brand: "Home Black",
				price: 30,
				quantity: 0,
				total: 0,
				prod_status: "pending",
			},
			{
				image: "/images/avocado.jpg",
				name: "Product2",
				brand: "Home Blue",
				price: 120,
				quantity: 3,
				total: 360,
				prod_status: "pending",
			},
			{
				image: "/images/apple.png",
				name: "Product4",
				brand: "Home Red",
				price: 300,
				quantity: 4,
				total: 1200,
				prod_status: "pending",
			},
			{
				image: "/images/avocado.jpg",
				name: "Product5",
				brand: "Home Black",
				price: 200,
				quantity: 10,
				total: 2000,
				prod_status: "pending",
			},
		],
	},
	{
		id: "order12555",
		supplier: "Order ABC",
		shipping_date: "Thu, Feb 11",
		total: 15000,
		categories: ["fruits", "vegitables"],
		department: "300-30-110",
		status: "Awaiting your approval",
		products: [
			{
				image: "/images/apple.png",
				name: "Product1",
				brand: "Home Black",
				price: 30,
				quantity: 0,
				total: 0,
				prod_status: "pending",
			},
			{
				image: "/images/avocado.jpg",
				name: "Product2",
				brand: "Home Blue",
				price: 120,
				quantity: 3,
				total: 360,
				prod_status: "pending",
			},
			{
				image: "/images/apple.png",
				name: "Product4",
				brand: "Home Red",
				price: 300,
				quantity: 4,
				total: 1200,
				prod_status: "pending",
			},
			{
				image: "/images/avocado.jpg",
				name: "Product5",
				brand: "Home Black",
				price: 200,
				quantity: 10,
				total: 2000,
				prod_status: "pending",
			},
		],
	},
	{
		id: "order1212",
		supplier: "East cost fruits4",
		shipping_date: "Thu, Feb 12",
		total: 15000,
		categories: ["fruits", "vegitables"],
		department: "300-30-1130",
		status: "Awaiting your approval",
		products: [
			{
				image: "/images/apple.png",
				name: "Product1",
				brand: "Home Black",
				price: 30,
				quantity: 0,
				total: 0,
				prod_status: "pending",
			},
			{
				image: "/images/avocado.jpg",
				name: "Product2",
				brand: "Home Blue",
				price: 120,
				quantity: 3,
				total: 360,
				prod_status: "pending",
			},
			{
				image: "/images/apple.png",
				name: "Product4",
				brand: "Home Red",
				price: 300,
				quantity: 4,
				total: 1200,
				prod_status: "pending",
			},
			{
				image: "/images/avocado.jpg",
				name: "Product5",
				brand: "Home Black",
				price: 200,
				quantity: 10,
				total: 2000,
				prod_status: "pending",
			},
		],
	},
];

export const EditReasons = [
	"Missing Product",
	"Quantity is not same",
	"Price is not same",
	"Other",
];
